### PR TITLE
Add typings

### LINKED ISSUE #11: Add typings
In order to increase usability, we should add typings.

### PR DESCRIPTION
**Pull request by TronchDeYack**
- Create typings declaration file
  - Add typings file in package.json

Close #11

### CODE REVIEW

**Review by vjarysta — APPROVED** [review]

**Comment by TronchDeYack** [comment]
Hi @ericelliott, could you review this PR please ? :D

**Review by tverhoken — APPROVED** [review]
👍

**Review by tverhoken — APPROVED** [review]
Yeah, better 👍

**Comment by ericelliott** [comment]
This library is not actively maintained. From the Readme:

> This library is a useful reference, but is no longer maintained for production use. It has been deprecated in favor of react-feature-toggles and [feature-toggles](https://github.com/paralleldrive/feature-toggles)

**Comment by tverhoken** [comment]
Alright, think you. We will see to migrate to the new one 😉

**Pull request closed without merging**
